### ISSUE TITLE
error - cannot load Sinatra

### ISSUE THREAD

**Issue by galaxymaster1** [Aeolyus/Pebble-PC-Controller#1]
hey,

i followed the steps but i cant get it to work it flashes a command prompt and i was lucky enough to get a screenshot saying that it cannot load Sinatra

hope to hear from you soon

**Comment by Aeolyus** [comment]
Hey galaxymaster1! Thanks for trying out my application. There might be a
few reasons that a command prompt flashes up. First of all, kill the server
in task manager. Then run the server in console mode by changing the name
"server.rbw" to "server.rb". Proceed to run the server again. The server
should now open a console in which every single button press on your Pebble
results in a number (0, 1, 2, 3) then some extra information. If within the
extra information it says there is an error loading something. That means
the file locations were inputted wrong in the server or that the names of
the scripts in the handlers folder in the server folder do not match up
with the names in the server. Make sure that these names are he same and
the file location is correct.

Tell me how it goes and if you still have questions or problems feel free
to contact me.

**Comment by galaxymaster1** [comment]
hey, i tried running in console mode and the command prompt didnt stay open, but it still flashes with the "cannot load such file - sinatra after i check the names and locations
![picture1](https://cloud.githubusercontent.com/assets/5687710/8797559/913f7532-2fdf-11e5-8856-daff49273a06.png)

**Comment by Aeolyus** [comment]
Make sure you have .NET installed. Can you also take a picture of your
server in notepad, tell me the version of Ruby you have, and show me the
location of the handler files.

.NET: https://www.microsoft.com/net

**Comment by Aeolyus** [comment]
I found out the error. You have to open cmd.exe with ruby and then do "gem
install sinatra". Sorry about that. I will include this in the instructions
for future reference.

On Tue, Jul 21, 2015 at 7:25 AM, Richard Huang <richardhuang.huang@gmail.com
